# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Test develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build And Test Xcode Project
      run: xcodebuild clean test -workspace AutoTest_GithubAction_iOS.xcworkspace -scheme AutoTest_GithubAction_iOS -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
        
    - name: Archive Xcode Project
      run: xcodebuild archive -project AutoTest_GithubAction_iOS.xcodeproj -scheme AutoTest_GithubAction_iOS -destination generic/platform=iOS -archivePath ./Build/AutoTest_GithubAction_iOS.xcarchive CODE_SIGNING_ALLOWED=NO

    - name: Export Archive as IPA
      run: xcodebuild -exportArchive -archivePath ./Build/AutoTest_GithubAction_iOS.xcarchive -exportPath ./Build -exportOptionsPlist ExportOptions.plist CODE_SIGNING_ALLOWED=NO

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AutoTest_GithubAction_iOS-IPA
        path: ./Build/AutoTest_GithubAction_iOS.ipa
